-- Converted using Mokiros's Model to Script Version 3
-- Converted string size: 32956 characters
local function DecodeUnion(Values,Flags,Parse,data)
	local m = Instance.new("Folder")
	m.Name = "UnionCache ["..tostring(math.random(1,9999)).."]"
	m.Archivable = false
	m.Parent = game:GetService("ServerStorage")
	local Union,Subtract = {},{}
	if not data then
		data = Parse('B')
	end
	local ByteLength = (data % 4) + 1
	local Length = Parse('I'..ByteLength)
	local ValueFMT = ('I'..Flags[1])
	for i = 1,Length do
		local data = Parse('B')
		local part
		local isNegate = bit32.band(data,0b10000000) > 0
		local isUnion =  bit32.band(data,0b01000000) > 0
		if isUnion then
			part = DecodeUnion(Values,Flags,Parse,data)
		else
			local isMesh = data % 2 == 1
			local ClassName = Values[Parse(ValueFMT)]
			part = Instance.new(ClassName)
			part.Size = Values[Parse(ValueFMT)]
			part.Position = Values[Parse(ValueFMT)]
			part.Orientation = Values[Parse(ValueFMT)]
			if isMesh then
				local mesh = Instance.new("SpecialMesh")
				mesh.MeshType = Values[Parse(ValueFMT)]
				mesh.Scale = Values[Parse(ValueFMT)]
				mesh.Offset = Values[Parse(ValueFMT)]
				mesh.Parent = part
			end
		end
		part.Parent = m
		table.insert(isNegate and Subtract or Union,part)
	end
	local first = table.remove(Union,1)
	if #Union>0 then
		first = first:UnionAsync(Union)
	end
	if #Subtract>0 then
		first = first:SubtractAsync(Subtract)
	end
	m:Destroy()
	return first
end

local function Decode(str)
	local StringLength = #str
	
	-- Base64 decoding
	do
		local decoder = {}
		for b64code, char in pairs(('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='):split('')) do
			decoder[char:byte()] = b64code-1
		end
		local n = StringLength
		local t,k = table.create(math.floor(n/4)+1),1
		local padding = str:sub(-2) == '==' and 2 or str:sub(-1) == '=' and 1 or 0
		for i = 1, padding > 0 and n-4 or n, 4 do
			local a, b, c, d = str:byte(i,i+3)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40 + decoder[d]
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8),bit32.extract(v,0,8))
			k = k + 1
		end
		if padding == 1 then
			local a, b, c = str:byte(n-3,n-1)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000 + decoder[c]*0x40
			t[k] = string.char(bit32.extract(v,16,8),bit32.extract(v,8,8))
		elseif padding == 2 then
			local a, b = str:byte(n-3,n-2)
			local v = decoder[a]*0x40000 + decoder[b]*0x1000
			t[k] = string.char(bit32.extract(v,16,8))
		end
		str = table.concat(t)
	end
	
	local Position = 1
	local function Parse(fmt)
		local Values = {string.unpack(fmt,str,Position)}
		Position = table.remove(Values)
		return table.unpack(Values)
	end
	
	local Settings = Parse('B')
	local Flags = Parse('B')
	Flags = {
		--[[ValueIndexByteLength]] bit32.extract(Flags,6,2)+1,
		--[[InstanceIndexByteLength]] bit32.extract(Flags,4,2)+1,
		--[[ConnectionsIndexByteLength]] bit32.extract(Flags,2,2)+1,
		--[[MaxPropertiesLengthByteLength]] bit32.extract(Flags,0,2)+1,
		--[[Use Double instead of Float]] bit32.band(Settings,0b1) > 0
	}
	
	local ValueFMT = ('I'..Flags[1])
	local InstanceFMT = ('I'..Flags[2])
	local ConnectionFMT = ('I'..Flags[3])
	local PropertyLengthFMT = ('I'..Flags[4])
	
	local ValuesLength = Parse(ValueFMT)
	local Values = table.create(ValuesLength)
	local CFrameIndexes = {}
	
	local ValueDecoders = {
		--!!Start
		[1] = function(Modifier)
			return Parse('s'..Modifier)
		end,
		--!!Split
		[2] = function(Modifier)
			return Modifier ~= 0
		end,
		--!!Split
		[3] = function()
			return Parse('d')
		end,
		--!!Split
		[4] = function(_,Index)
			table.insert(CFrameIndexes,{Index,Parse(('I'..Flags[1]):rep(3))})
		end,
		--!!Split
		[5] = {CFrame.new,Flags[5] and 'dddddddddddd' or 'ffffffffffff'},
		--!!Split
		[6] = {Color3.fromRGB,'BBB'},
		--!!Split
		[7] = {BrickColor.new,'I2'},
		--!!Split
		[8] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = ColorSequenceKeypoint.new(Parse('f'),Color3.fromRGB(Parse('BBB')))
			end
			return ColorSequence.new(kpts)
		end,
		--!!Split
		[9] = function(Modifier)
			local len = Parse('I'..Modifier)
			local kpts = table.create(len)
			for i = 1,len do
				kpts[i] = NumberSequenceKeypoint.new(Parse(Flags[5] and 'ddd' or 'fff'))
			end
			return NumberSequence.new(kpts)
		end,
		--!!Split
		[10] = {Vector3.new,Flags[5] and 'ddd' or 'fff'},
		--!!Split
		[11] = {Vector2.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[12] = {UDim2.new,Flags[5] and 'di2di2' or 'fi2fi2'},
		--!!Split
		[13] = {Rect.new,Flags[5] and 'dddd' or 'ffff'},
		--!!Split
		[14] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Axes.new(unpack(t))
		end,
		--!!Split
		[15] = function()
			local flags = Parse('B')
			local ids = {"Top","Bottom","Left","Right","Front","Back"}
			local t = {}
			for i = 0,5 do
				if bit32.extract(flags,i,1)==1 then
					table.insert(t,Enum.NormalId[ids[i+1]])
				end
			end
			return Faces.new(unpack(t))
		end,
		--!!Split
		[16] = {PhysicalProperties.new,Flags[5] and 'ddddd' or 'fffff'},
		--!!Split
		[17] = {NumberRange.new,Flags[5] and 'dd' or 'ff'},
		--!!Split
		[18] = {UDim.new,Flags[5] and 'di2' or 'fi2'},
		--!!Split
		[19] = function()
			return Ray.new(Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')),Vector3.new(Parse(Flags[5] and 'ddd' or 'fff')))
		end
		--!!End
	}
	
	for i = 1,ValuesLength do
		local TypeAndModifier = Parse('B')
		local Type = bit32.band(TypeAndModifier,0b11111)
		local Modifier = (TypeAndModifier - Type) / 0b100000
		local Decoder = ValueDecoders[Type]
		if type(Decoder)=='function' then
			Values[i] = Decoder(Modifier,i)
		else
			Values[i] = Decoder[1](Parse(Decoder[2]))
		end
	end
	
	for i,t in pairs(CFrameIndexes) do
		Values[t[1]] = CFrame.fromMatrix(Values[t[2]],Values[t[3]],Values[t[4]])
	end
	
	local InstancesLength = Parse(InstanceFMT)
	local Instances = {}
	local NoParent = {}
	
	for i = 1,InstancesLength do
		local ClassName = Values[Parse(ValueFMT)]
		local obj
		local MeshPartMesh,MeshPartScale
		if ClassName == "UnionOperation" then
			obj = DecodeUnion(Values,Flags,Parse)
			obj.UsePartColor = true
		elseif ClassName:find("Script") then
			obj = Instance.new("Folder")
			Script(obj,ClassName=='ModuleScript')
		elseif ClassName == "MeshPart" then
			obj = Instance.new("Part")
			MeshPartMesh = Instance.new("SpecialMesh")
			MeshPartMesh.MeshType = Enum.MeshType.FileMesh
			MeshPartMesh.Parent = obj
		else
			obj = Instance.new(ClassName)
		end
		local Parent = Instances[Parse(InstanceFMT)]
		local PropertiesLength = Parse(PropertyLengthFMT)
		local AttributesLength = Parse(PropertyLengthFMT)
		Instances[i] = obj
		for i = 1,PropertiesLength do
			local Prop,Value = Values[Parse(ValueFMT)],Values[Parse(ValueFMT)]
			
			-- ok this looks awful
			if MeshPartMesh then
				if Prop == "MeshId" then
					MeshPartMesh.MeshId = Value
					continue
				elseif Prop == "TextureID" then
					MeshPartMesh.TextureId = Value
					continue
				elseif Prop == "Size" then
					if not MeshPartScale then
						MeshPartScale = Value
					else
						MeshPartMesh.Scale = Value / MeshPartScale
					end
				elseif Prop == "MeshSize" then
					if not MeshPartScale then
						MeshPartScale = Value
						MeshPartMesh.Scale = obj.Size / Value
					else
						MeshPartMesh.Scale = MeshPartScale / Value
					end
					continue
				end
			end
			
			obj[Prop] = Value
		end
		if MeshPartMesh then
			if MeshPartMesh.MeshId=='' then
				if MeshPartMesh.TextureId=='' then
					MeshPartMesh.TextureId = 'rbxasset://textures/meshPartFallback.png'
				end
				MeshPartMesh.Scale = obj.Size
			end
		end
		for i = 1,AttributesLength do
			obj:SetAttribute(Values[Parse(ValueFMT)],Values[Parse(ValueFMT)])
		end
		if not Parent then
			table.insert(NoParent,obj)
		else
			obj.Parent = Parent
		end
	end
	
	local ConnectionsLength = Parse(ConnectionFMT)
	for i = 1,ConnectionsLength do
		local a,b,c = Parse(InstanceFMT),Parse(ValueFMT),Parse(InstanceFMT)
		Instances[a][Values[b]] = Instances[c]
	end
	
	return NoParent
end


local Objects = Decode('AFB6AyEFTW9kZWwhBE5hbWUhBk9iYnkgMSEKV29ybGRQaXZvdARDA0QDRQMhBkZvbGRlciEEQmFzZSEEUGFydCEIQW5jaG9yZWQiIQ1Cb3R0b21TdXJmYWNlAwAAAAAAAAAAIQpCcmlja0NvbG9yB+oDIQZDRnJhbWUEGABEA0UDIQVDb2xvcgbNzc0hCE1hdGVyaWFsAwAAAAAAAHFAIQtPcml'
..'lbnRhdGlvbgoAAAAAAAC0QgAAAAAhCFBvc2l0aW9uCgJABsMAw3U//n8SwyEIUm90YXRpb24hBFNpemUKAAAoQgAAgD8AAFBBIQpUb3BTdXJmYWNlBB4ARANFAwoEgPDCAMN1P/7/GMMKAADoQQAAgD8AAHBBIQlXZWRnZVBhcnQEIgBEA0UDCgJADcMAw3U//n8SwwoAAChCAACAPwAAgD8EJg'
..'BGA0UDCgAAAAAAADTDAAAAAAoCQAbDAMN1P/z/+cIKAAA0wwAAAAAAADTDCgAAUEEAAIA/AACAPwQrAEcDRQMKAAAAAAAAtMIAAAAACgSA4MIAw3U//v8YwwoAAOhBAACAPwAAgD8ELgBHA0UDCgSA/sIAw3U//n8DwwoAAEBBAACAPwAAgD8EMQBGA0UDCgSA78IAw3U//v8JwwoAAGBBAACAP'
..'wAAgD8ENABGA0UDCgSA/sIAw3U//v8JwwoAAIA/AACAPwAAgD8ENABHA0UDBDgASANFAwoEgP3CAMN1P/7/J8MKAADgQQAAgD8AAIA/IQ5JbnZlcnRlZFdlZGdlcyEOVW5pb25PcGVyYXRpb24hDUludmVydGVkV2VkZ2UEPwBIA0QDCgAAtMIAAAAAAAAAAAoEgODCAMN1P/7/CcMKAACAPwAA'
..'gD/8/38/CgSA4ML4wnU//v8JwwoEgODCBMN1P/7/CcMERQBEA0YDCgAAtMIAALRCAAAAAAoEgODCAMN1P/7/J8MKAAC0wgAAAAAAALRCCgSA4ML4wnU//v8nwwoEgODCBMN1P/7/J8MKAAAAAAAAAAAAAAAABEwARgNHAwoAALTCAAA0wwAAAAAKAkANwwDDdT/+/yfDCgAAtMIAAAAAAAA0wwo'
..'CQA3D+MJ1P/7/J8MKAkANwwTDdT/+/yfDBFIARwNIAwoAALTCAAC0wgAAAAAKAkANwwDDdT/8//nCCgAAtMIAAAAAAAC0wgoCQA3D+MJ1P/z/+cIKAkANwwTDdT/8//nCBFcASANEAwoEgP7CAMN1P/z/+cIKBID+wvjCdT/8//nCCgSA/sIEw3U//P/5wiEIQmxvY2tlcnMhB0Jsb2NrZXIESQ'
..'NGA0UDIQVUaGluZwRKA0YDRQMEYABGA0cDCgJABMOA4fo//v8EwwoCQATDfOH6P/7/BMMKAkAEw4Lh+j/+/wTDBGQARwNIAwoCQATDgOH6P/7/AsMKAkAEw3zh+j/+/wLDCgJABMOC4fo//v8CwwRoAEgDRAMKAkAAw4Dh+j/+/wLDCgJAAMN84fo//v8CwwoCQADDguH6P/7/AsMEbABEA0YDC'
..'gJAAMOA4fo//v8EwwoCQADDfOH6P/7/BMMKAkAAw4Lh+j/+/wTDBHAARgNFAwoCQALDgOH6P/7/AsMKAABAQAAAgD8AAIA/BHMASANFAwoCQALDgOH6P/7/BMMEdQBEA0UDCgJABMOA4fo//v8DwwR3AEcDRQMKAkAAw4Dh+j/+/wPDBHkARANFAwoCQALDMGB3Qf7/A8MKAACAPwAA4EEAAEBA'
..'BEsDSANMAwR+AEgDRwMKAAC0QgAAAAAAAAAACgJAAMMYrudB/v8EwwoAAAAAAAC0wgAANEMEggBHA0YDCgAAtEIAALTCAAAAAAoCQADDGK7nQf7/AsMKAAC0QgAAAAAAALRCCgAAAAAAADTDAAA0QwSHAEYDRAMKAAC0QgAANMMAAAAACgJABMMYrudB/v8CwwoAALRCAAAAAAAANEMKAAAAAAA'
..'AtEIAADRDBIwARANIAwoAALRCAAC0QgAAAAAKAkAEwxiu50H+/wTDCgAAtEIAAAAAAAC0wgoAAAAAAAAAAAAANEMEkABIA0wDCgJAAsMYrudB/v8CwwoAADTDAAAAAAAAAAAEkwBGA0wDCgJAAsMYrudB/v8EwwoAAAAAAAAAAAAANMMElgBEA0wDCgJAAMMYrudB/v8DwwoAADTDAAC0wgAAAA'
..'AEmQBHA0wDCgJABMMYrudB/v8DwwoAADRDAAC0QgAAAAAEnABEA0UDCgSA/sIM1xNC/v8HwwoAAIA/AABQQQAAiEEhDFRyYW5zcGFyZW5jeQMAAADAzMzsPwShAEQDRQMKAkABwwzXE0L+/xLDCgAAgD8AAFBBAAC4QSEJUGxhdGZvcm1zIQlQbGF0Zm9ybTIETQNEA0UDBKcARANFAwoEgPLCY'
..'MDuQP7/IsMKAACAPwAAQEEAAIA/BE4DRgNHAwSrAEYDRwMKBID0woDh+j/+/yPDCgSA9MJ84fo//v8jwwoEgPTCguH6P/7/I8MErwBHA0gDCgSA9MKA4fo//v8hwwoEgPTCfOH6P/7/IcMKBID0woLh+j/+/yHDBLMASANEAwoEgPDCgOH6P/7/IcMKBIDwwnzh+j/+/yHDCgSA8MKC4fo//v8h'
..'wwS3AEYDRQMKBIDywoDh+j/+/yHDBLkARwNFAwoEgPDCgOH6P/7/IsMEuwBEA0YDCgSA8MKA4fo//v8jwwoEgPDCfOH6P/7/I8MKBIDwwoLh+j/+/yPDBL8ASANFAwoEgPLCgOH6P/7/I8MEwQBEA0UDCgSA9MKA4fo//v8iwwRPA0gDRwMExABIA0cDCgSA8MIwXE9B/v8jwwoEgPDCMVxPQf7'
..'/I8MExwBHA0YDCgSA8MIwXE9B/v8hwwoEgPDCMVxPQf7/IcMEygBGA0QDCgSA9MIwXE9B/v8hwwoEgPTCMVxPQf7/IcMEzQBIA0wDCgSA8sIwXE9B/v8hwwTPAEcDTAMKBID0wjBcT0H+/yLDBNEARANIAwoEgPTCMFxPQf7/I8MKBID0wjFcT0H+/yPDBNQARgNMAwoEgPLCMFxPQf7/I8ME1g'
..'BEA0wDCgSA8MIwXE9B/v8iwyEJUGxhdGZvcm0xBFADRANFAwTaAEQDRQMKBIDmwsBwfUD+/yTDCgAAgD8AAKBAAACAPwRRA0gDRwME3gBIA0cDCgSA5MJguL5A/v8lwwoEgOTCYri+QP7/JcME4QBHA0YDCgSA5MJguL5A/v8jwwoEgOTCYri+QP7/I8ME5ABGA0QDCgSA6MJguL5A/v8jwwoEg'
..'OjCYri+QP7/I8ME5wBIA0wDCgSA5sJguL5A/v8jwwTpAEcDTAMKBIDowmC4vkD+/yTDBOsARANIAwoEgOjCYLi+QP7/JcMKBIDowmK4vkD+/yXDBO4ARgNMAwoEgObCYLi+QP7/JcME8ABEA0wDCgSA5MJguL5A/v8kwwRSA0YDRwME8wBGA0cDCgSA6MKA4fo//v8lwwoEgOjCfOH6P/7/JcMK'
..'BIDowoLh+j/+/yXDBPcARwNIAwoEgOjCgOH6P/7/I8MKBIDownzh+j/+/yPDCgSA6MKC4fo//v8jwwT7AEgDRAMKBIDkwoDh+j/+/yPDCgSA5MJ84fo//v8jwwoEgOTCguH6P/7/I8ME/wBGA0UDCgSA5sKA4fo//v8jwwQBAUcDRQMKBIDkwoDh+j/+/yTDBAMBRANGAwoEgOTCgOH6P/7/JcM'
..'KBIDkwnzh+j/+/yXDCgSA5MKC4fo//v8lwwQHAUgDRQMKBIDmwoDh+j/+/yXDBAkBRANFAwoEgOjCgOH6P/7/JMMEDQFEA0UDIQpDYW5Db2xsaWRlAgoEgObCGK63Qf7/JMMKAACAPwAABEIAAIA/BFMDSANHAwQRAUgDRwMKBIDkwgzXG0L+/yXDBBMBRwNGAwoEgOTCDNcbQv7/I8MEFQFGA0'
..'QDCgSA6MIM1xtC/v8jwwQXAUgDTAMKBIDmwgzXG0L+/yPDBBkBRwNMAwoEgOjCDNcbQv7/JMMEGwFEA0gDCgSA6MIM1xtC/v8lwwQdAUYDTAMKBIDmwgzXG0L+/yXDBB8BRANMAwoEgOTCDNcbQv7/JMMhCVBsYXRmb3JtMwRUA0QDRQMEIwFEA0UDCgSA5sIwYBdB/v8cwwoAAIA/AACAQQAAg'
..'D8EVQNGA0cDBCcBRgNHAwoEgOjCgOH6P/7/HcMKBIDownzh+j/+/x3DCgSA6MKC4fo//v8dwwQrAUcDSAMKBIDowoDh+j/+/xvDCgSA6MJ84fo//v8bwwoEgOjCguH6P/7/G8MELwFIA0QDCgSA5MKA4fo//v8bwwoEgOTCfOH6P/7/G8MKBIDkwoLh+j/+/xvDBDMBRgNFAwoEgObCgOH6P/7/'
..'G8MENQFHA0UDCgSA5MKA4fo//v8cwwQ3AUQDRgMKBIDkwoDh+j/+/x3DCgSA5MJ84fo//v8dwwoEgOTCguH6P/7/HcMEOwFIA0UDCgSA5sKA4fo//v8dwwQ9AUQDRQMKBIDowoDh+j/+/xzDBFYDSANHAwRAAUgDRwMKBIDkwhiuh0H+/x3DBEIBRwNGAwoEgOTCGK6HQf7/G8MERAFGA0QDCgS'
..'A6MIYrodB/v8bwwRGAUgDTAMKBIDmwhiuh0H+/xvDBEgBRwNMAwoEgOjCGK6HQf7/HMMESgFEA0gDCgSA6MIYrodB/v8dwwRMAUYDTAMKBIDmwhiuh0H+/x3DBE4BRANMAwoEgOTCGK6HQf7/HMMhCVBsYXRmb3JtNARXA0QDRQMEUgFEA0UDCgSA5sIwYBdB/v8RwwRYA0YDRwMEVQFGA0cDCg'
..'SA6MKA4fo//v8SwwoEgOjCfOH6P/7/EsMKBIDowoLh+j/+/xLDBFkBRwNIAwoEgOjCgOH6P/7/EMMKBIDownzh+j/+/xDDCgSA6MKC4fo//v8QwwRdAUgDRAMKBIDkwoDh+j/+/xDDCgSA5MJ84fo//v8QwwoEgOTCguH6P/7/EMMEYQFGA0UDCgSA5sKA4fo//v8QwwRjAUcDRQMKBIDkwoDh+'
..'j/+/xHDBGUBRANGAwoEgOTCgOH6P/7/EsMKBIDkwnzh+j/+/xLDCgSA5MKC4fo//v8SwwRpAUgDRQMKBIDmwoDh+j/+/xLDBGsBRANFAwoEgOjCgOH6P/7/EcMEWQNIA0cDBG4BSANHAwoEgOTCGK6HQf7/EsMEcAFHA0YDCgSA5MIYrodB/v8QwwRyAUYDRAMKBIDowhiuh0H+/xDDBHQBSANM'
..'AwoEgObCGK6HQf7/EMMEdgFHA0wDCgSA6MIYrodB/v8RwwR4AUQDSAMKBIDowhiuh0H+/xLDBHoBRgNMAwoEgObCGK6HQf7/EsMEfAFEA0wDCgSA5MIYrodB/v8RwyEJUGxhdGZvcm03BFoDRANFAwSAAUQDRQMKAkACwzBgN0H8///CCgAAgD8AAKBBAACAPwRbA0YDRwMEhAFGA0cDCgJAA8O'
..'A4fo//v8AwwoCQAPDfOH6P/7/AMMKAkADw4Lh+j/+/wDDBIgBRwNIAwoCQAPDgOH6P/z//cIKAkADw3zh+j/8//3CCgJAA8OC4fo//P/9wgSMAUgDRAMKAkABw4Dh+j/8//3CCgJAAcN84fo//P/9wgoCQAHDguH6P/z//cIEkAFGA0UDCgJAAsOA4fo//P/9wgSSAUcDRQMKAkABw4Dh+j/8//'
..'/CBJQBRANGAwoCQAHDgOH6P/7/AMMKAkABw3zh+j/+/wDDCgJAAcOC4fo//v8AwwSYAUgDRQMKAkACw4Dh+j/+/wDDBJoBRANFAwoCQAPDgOH6P/z//8IEXANIA0cDBJ0BSANHAwoCQAHDGK6nQf7/AMMEnwFHA0YDCgJAAcMYrqdB/P/9wgShAUYDRAMKAkADwxiup0H8//3CBKMBSANMAwoCQ'
..'ALDGK6nQfz//cIEpQFHA0wDCgJAA8MYrqdB/P//wgSnAUQDSAMKAkADwxiup0H+/wDDBKkBRgNMAwoCQALDGK6nQf7/AMMEqwFEA0wDCgJAAcMYrqdB/P//wiEJUGxhdGZvcm01BF0DSANMAwReA0gDTAMEsAFIA0wDCgSA9MIYrudB/v8LwwoAAHBBAACAPwAAgD8EswFHA0YDCgiA5MIYrudB'
..'/v8LwwS1AUQDTAMKBIDkwhiu50H+/wzDBLcBSANHAwoIgOTCGK7nQf7/DcMEuQFGA0wDCgSA9MIYrudB/v8NwwS7AUQDSAMKAkACwxiu50H+/w3DBL0BRwNMAwoCQALDGK7nQf7/DMMEvwFGA0QDCgJAAsMYrudB/v8LwwTBAUQDRQMKBID0wjBgd0H+/wzDCgAAgD8CAOBBAABwQQTEAUQDRQM'
..'KBIDzwhiuh0H+/w3DCgAAgD8GAIA/AAAAQARfA0YDRQMEyAFGA0UDCgSA9MKA4fo//v8LwwTKAUcDSAMKAkACw4Dh+j/+/wvDCgJAAsN84fo//v8LwwoCQALDguH6P/7/C8MEzgFEA0UDCgJAAsOA4fo//v8MwwTQAUYDRwMKAkACw4Dh+j/+/w3DCgJAAsN84fo//v8NwwoCQALDguH6P/7/Dc'
..'ME1AFIA0UDCgSA9MKA4fo//v8NwwTWAUQDRgMKBIDkwoDh+j/+/w3DCgSA5MJ84fo//v8NwwoEgOTCguH6P/7/DcME2gFHA0UDCgSA5MKA4fo//v8MwwTcAUgDRAMKBIDkwoDh+j/+/wvDCgSA5MJ84fo//v8LwwoEgOTCguH6P/7/C8ME4AFEA0UDCgJAAcMYrodB/v8MwwoAAEBABgCAPwAAQ'
..'EAhCVBsYXRmb3JtNgRgA0QDRQME5QFEA0UDCgJAAsMwYBdB/v8HwwRhA0YDRwME6AFGA0cDCgJAA8OA4fo//v8IwwoCQAPDfOH6P/7/CMMKAkADw4Lh+j/+/wjDBOwBRwNIAwoCQAPDgOH6P/7/BsMKAkADw3zh+j/+/wbDCgJAA8OC4fo//v8GwwTwAUgDRAMKAkABw4Dh+j/+/wbDCgJAAcN8'
..'4fo//v8GwwoCQAHDguH6P/7/BsME9AFGA0UDCgJAAsOA4fo//v8GwwT2AUcDRQMKAkABw4Dh+j/+/wfDBPgBRANGAwoCQAHDgOH6P/7/CMMKAkABw3zh+j/+/wjDCgJAAcOC4fo//v8IwwT8AUgDRQMKAkACw4Dh+j/+/wjDBP4BRANFAwoCQAPDgOH6P/7/B8MEYgNIA0cDBAECSANHAwoCQAH'
..'DGK6HQf7/CMMEAwJHA0YDCgJAAcMYrodB/v8GwwQFAkYDRAMKAkADwxiuh0H+/wbDBAcCSANMAwoCQALDGK6HQf7/BsMECQJHA0wDCgJAA8MYrodB/v8HwwQLAkQDSAMKAkADwxiuh0H+/wjDBA0CRgNMAwoCQALDGK6HQf7/CMMEDwJEA0wDCgJAAcMYrodB/v8HwyEJUGxhdGZvcm04BGMDRA'
..'NFAwQTAkQDRQMKAkAKwzBgd0H+/wPDCgAAgD8AAOBBAACAPwRkA0YDRwMEFwJGA0cDCgJAC8OA4fo//v8EwwoCQAvDfOH6P/7/BMMKAkALw4Lh+j/+/wTDBBsCRwNIAwoCQAvDgOH6P/7/AsMKAkALw3zh+j/+/wLDCgJAC8OC4fo//v8CwwQfAkgDRAMKAkAJw4Dh+j/+/wLDCgJACcN84fo//'
..'v8CwwoCQAnDguH6P/7/AsMEIwJGA0UDCgJACsOA4fo//v8CwwQlAkcDRQMKAkAJw4Dh+j/+/wPDBCcCRANGAwoCQAnDgOH6P/7/BMMKAkAJw3zh+j/+/wTDCgJACcOC4fo//v8EwwQrAkgDRQMKAkAKw4Dh+j/+/wTDBC0CRANFAwoCQAvDgOH6P/7/A8MEZQNIA0cDBDACSANHAwoCQAnDGK7n'
..'Qf7/BMMEMgJHA0YDCgJACcMYrudB/v8CwwQ0AkYDRAMKAkALwxiu50H+/wLDBDYCSANMAwoCQArDGK7nQf7/AsMEOAJHA0wDCgJAC8MYrudB/v8DwwQ6AkQDSAMKAkALwxiu50H+/wTDBDwCRgNMAwoCQArDGK7nQf7/BMMEPgJEA0wDCgJACcMYrudB/v8DwyEJUGxhdGZvcm05BGYDRANFAwR'
..'CAkQDRQMKAkAKwzBgd0H+/wzDBGcDRgNHAwRFAkYDRwMKAkALw4Dh+j/+/w3DCgJAC8N84fo//v8NwwoCQAvDguH6P/7/DcMESQJHA0gDCgJAC8OA4fo//v8LwwoCQAvDfOH6P/7/C8MKAkALw4Lh+j/+/wvDBE0CSANEAwoCQAnDgOH6P/7/C8MKAkAJw3zh+j/+/wvDCgJACcOC4fo//v8Lww'
..'RRAkYDRQMKAkAKw4Dh+j/+/wvDBFMCRwNFAwoCQAnDgOH6P/7/DMMEVQJEA0YDCgJACcOA4fo//v8NwwoCQAnDfOH6P/7/DcMKAkAJw4Lh+j/+/w3DBFkCSANFAwoCQArDgOH6P/7/DcMEWwJEA0UDCgJAC8OA4fo//v8MwwRoA0gDRwMEXgJIA0cDCgJACcMYrudB/v8NwwRgAkcDRgMKAkAJw'
..'xiu50H+/wvDBGICRgNEAwoCQAvDGK7nQf7/C8MEZAJIA0wDCgJACsMYrudB/v8LwwRmAkcDTAMKAkALwxiu50H+/wzDBGgCRANIAwoCQAvDGK7nQf7/DcMEagJGA0wDCgJACsMYrudB/v8NwwRsAkQDTAMKAkAJwxiu50H+/wzDIQpQbGF0Zm9ybTExBGkDRgNMAwRwAkQDRQMKAkAGwxiuh0H+'
..'/xbDCgAAgD8AAPhBAACAPwRqA0YDRwMEdAJGA0cDCgJAB8OA4fo//v8XwwoCQAfDfOH6P/7/F8MKAkAHw4Lh+j/+/xfDBHgCRwNIAwoCQAfDgOH6P/7/FcMKAkAHw3zh+j/+/xXDCgJAB8OC4fo//v8VwwR8AkgDRAMKAkAFw4Dh+j/+/xXDCgJABcN84fo//v8VwwoCQAXDguH6P/7/FcMEgAJ'
..'GA0UDCgJABsOA4fo//v8VwwSCAkcDRQMKAkAFw4Dh+j/+/xbDBIQCRANGAwoCQAXDgOH6P/7/F8MKAkAFw3zh+j/+/xfDCgJABcOC4fo//v8XwwSIAkgDRQMKAkAGw4Dh+j/+/xfDBIoCRANFAwoCQAfDgOH6P/7/FsMEawNGA0wDBI0CRwNGAwoCQAXDGK7/Qf7/FcMEjwJGA0QDCgJAB8MYrv'
..'9B/v8VwwSRAkgDTAMKAkAGwxiu/0H+/xXDBJMCRwNMAwoCQAfDGK7/Qf7/FsMElQJEA0gDCgJAB8MYrv9B/v8XwwSXAkYDTAMKAkAGwxiu/0H+/xrDCgAAgD8AAIA/AADgQASaAkQDTAMKAkAFwxiu/0H+/xbDBJwCSANHAwoCQAXDGK7/Qf7/F8MhClBsYXRmb3JtMTAEbANEA0UDBKACRANFA'
..'woEgObCMFx/Qf7/FsMKAACAPwAA6EEAAIA/BG0DRgNHAwSkAkYDRwMKBIDowoDh+j/+/xfDCgSA6MJ84fo//v8XwwoEgOjCguH6P/7/F8MEqAJHA0gDCgSA6MKA4fo//v8VwwoEgOjCfOH6P/7/FcMKBIDowoLh+j/+/xXDBKwCSANEAwoEgOTCgOH6P/7/FcMKBIDkwnzh+j/+/xXDCgSA5MKC'
..'4fo//v8VwwSwAkYDRQMKBIDmwoDh+j/+/xXDBLICRwNFAwoEgOTCgOH6P/7/FsMEtAJEA0YDCgSA5MKA4fo//v8XwwoEgOTCfOH6P/7/F8MKBIDkwoLh+j/+/xfDBLgCSANFAwoEgObCgOH6P/7/F8MEugJEA0UDCgSA6MKA4fo//v8WwwTNAkgDRwMEvQJIA0cDCgSA5MIYrvdB/v8XwwS/Akc'
..'DRgMKBIDkwhiu90H+/xXDBMECRgNEAwoEgOjCGK73Qf7/FcMEwwJIA0wDCgSA5sIYrvdB/v8VwwTFAkcDTAMKBIDowhiu90H+/xbDBMcCRANIAwoEgOjCGK73Qf7/F8MEyQJGA0wDCgSA5sIYrvdB/v8XwwTLAkQDTAMKBIDkwhiu90H+/xbDBM0CRANFAwoEgObCGK73Qf7/FsMKAACAP/7/fz'
..'8AAIA/IQpQbGF0Zm9ybTEyBG4DRANFAwTSAkQDRQMKAkAGwxiwi0H+/yTDCgAAgD8AAABCAACAPwRvA0YDRwME1gJGA0cDCgJAB8OA4fo//v8lwwoCQAfDfOH6P/7/JcMKAkAHw4Lh+j/+/yXDBNoCRwNIAwoCQAfDgOH6P/7/I8MKAkAHw3zh+j/+/yPDCgJAB8OC4fo//v8jwwTeAkgDRAMKA'
..'kAFw4Dh+j/+/yPDCgJABcN84fo//v8jwwoCQAXDguH6P/7/I8ME4gJGA0UDCgJABsOA4fo//v8jwwTkAkcDRQMKAkAFw4Dh+j/+/yTDBOYCRANGAwoCQAXDgOH6P/7/JcMKAkAFw3zh+j/+/yXDCgJABcOC4fo//v8lwwTqAkgDRQMKAkAGw4Dh+j/+/yXDBOwCRANFAwoCQAfDgOH6P/7/JMME'
..'cANIA0cDBO8CSANHAwoCQAXDDNcDQv7/JcME8QJHA0YDCgJABcMM1wNC/v8jwwTzAkYDRAMKAkAHwwzXA0L+/yPDBPUCSANMAwoCQAbDDNcDQv7/I8ME9wJHA0wDCgJAB8MM1wNC/v8kwwT5AkQDSAMKAkAHwwzXA0L+/yXDBPsCRgNMAwoCQAbDDNcDQv7/JcME/QJEA0wDCgJABcMM1wNC/v8'
..'kwyEFVmluZTIEcQNEA3IDIQRWaW5lBAMDRANzAwpcj/jBAAC0QgAAAAAKWInqwpwGGUL+/yTDCgAAtMJSuGtCAAC0QgoAAIA/AACAPwAAQEAECANEA3QDCkjhwsEAALRCAAAAAAqsvu/CnJYTQv7/JMMKAAC0wq5Hg0IAALRCBAwDRANyAwpSuI7BAAC0QgAAAAAKCBX5wozmDEL+/yTDCgAAtM'
..'LsUZBCAAC0QgoAAIA/AACAPx+F40AEEQNEA3UDCkjhXsEAALRCAAAAAAqW4wLDLKoFQv7/JMMKAAC0wtcjmEIAALRCCgAAgD8AAIA/9ijMQCEFVmluZTEEdgNEA3cDBBgDRAN4AwoUrgPBAAC0QgAAAAAKmKXqwhjw9UH+/xbDCgAAtMI9iqNCAAC0QgQcA0QDeQMKXI/CvwAAtEIAAAAACqiA8'
..'MI4APRB/v8WwwoAALTCw/WwQgAAtEIEIANEA3cDCuxRoEAAALRCAAAAAAq4Z/rCGDD2Qf7/FsMKAAC0QuH6qUIAALTCBCQDRAN6AwpSuA5BAAC0QgAAAAAKRDYDwzjf+0H+/xbDCgAAtEL2KKJCAAC0wgoAAIA/AACAP7/1qEAhBlJhdGluZwf7AwQsA0QDRQMGAP//AwAAAAAAAHJACgSA/cIA'
..'Xw8//v8pwwoAAIA/zcxMPgAAAEIELwNEA0UDCgSA3MIAXw8//n8ZwwoAAAhCzcxMPgAAgD8EMgNEA0UDCgSA6sIAXw8//v8HwwoAAIA/zcxMPgAAcEEENQNEA0UDCgSA+sIAXw8//v8BwwoAAFBBzcxMPgAAgD8EOANEA0UDCgLABcMAXw8//P/1wgoAAIA/zcxMPgAAkEEEOwNEA0UDCgJAD8M'
..'AXw8//n8SwwoAAEBCzcxMPgAAgD8hBkZpbmlzaAf8AwRBA0QDRQMGAP8ACgSA5sKcCh5C/v8kwwr+//8/wczMPf7//z8KBID9whiur0H+fxLDCgAAILQAAAAAAACAvwoAAAAAAACAPwAAAAAKAACAvwAAAAAAACA0CgAAIDQAAAAAAACAPwoAAIA/AAAAAAAAILQKAkACwzBed0H+/wPDCgJAAs'
..'OA4fo//v8DwwoCQALDGK7nQf7/A8MKAAAAAAAAgL8AAACACgSA8sJgvO5A/v8iwwoEgPLCgOH6P/7/IsMKBIDywjBcT0H+/yLDCgSA5sIYrqNB/v8kwwoEgObCYLi+QP7/JMMKBIDmwoDh+j/+/yTDCgSA5sIM1xtC/v8kwwoEgObCMF4XQf7/HMMKBIDmwoDh+j/+/xzDCgSA5sIYrodB/v8cw'
..'woEgObCMF4XQf7/EcMKBIDmwoDh+j/+/xHDCgSA5sIYrodB/v8RwwoCQALDMF43Qfz//8IKAkACw4Dh+j/8///CCgJAAsMYrqdB/P//wgoEgPTCMF53Qf7/DMMKBID0whiu50H+/wzDCgSA9MKA4fo//v8MwwoCQALDMF4XQf7/B8MKAkACw4Dh+j/+/wfDCgJAAsMYrodB/v8HwwoCQArDMF53'
..'Qf7/A8MKAkAKw4Dh+j/+/wPDCgJACsMYrudB/v8DwwoCQArDMF53Qf7/DMMKAkAKw4Dh+j/+/wzDCgJACsMYrudB/v8MwwoCQAbDGK6HQf7/GcMKAkAGw4Dh+j/+/xbDCgJABsMYrv9B/v8ZwwoEgObCGK6DQf7/FsMKBIDmwoDh+j/+/xbDCgJABsMYr4tB/v8kwwoCQAbDgOH6P/7/JMMKAkA'
..'GwwzXA0L+/yTDCljA+cIciA5C/v8kwwpd3py+PrBzP/QVRDMK3SIEvzFDWz+UK6UzCoU00745NGk/0wCEMwpIiXa+Rnh4P80VGjMKxJz5wljX+UH+/xbDCjuysj0OBn8/yl5fsgroihK+cl19P6IttzIKS6XYvBTpfz9PZ4cxCiC0Hj4h6Hw/KGHGsjkBAQAAAAIAAgADAAQABQAGAAEAAQACAA'
..'cACAACAAwAAgAHAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAWABoAGwAcAAwACAACAAwAAgAHAAkACgALAAwADQAOAA8AHQARABIAEwAUABUAFgAXAB4AGQAWABoAHwAcAAwAIAACAAoACQAKAAsADAANAA4ADwAhABEAEgATABQAFQAWABcAIgAZABYAGgAjACAAAgAKAAkAC'
..'gALAAwADQAOAA8AJAARABIAEwAUABUAJQAXACYAGQAnABoAKAAgAAIACgAJAAoACwAMAA0ADgAPACkAEQASABMAFAAVACoAFwArABkAKgAaACwAIAACAAoACQAKAAsADAANAA4ADwAtABEAEgATABQAFQAqABcALgAZACoAGgAvACAAAgAKAAkACgALAAwADQAOAA8AMAARABIAEwAUABUAJQAX'
..'ADEAGQAnABoAMgAgAAIACgAJAAoACwAMAA0ADgAPADMAEQASABMAFAAVACUAFwA0ABkAJwAaADUAIAACAAoACQAKAAsADAANAA4ADwA2ABEAEgATABQAFQAqABcANAAZACoAGgA1ACAAAgAIAAkACgALAAwADQAOAA8ANwARABIAEwAUABcAOAAaADkABgACAAEAAgA6ADsAQAKAIAA1AEEAPgA'
..'AIAA1AEIAKgANAAoAAgA8AAkACgANAA4ADwA9ABEAEgATABQAFQA+ABcAPwAZAD4AGgBAADsAQAKAIAA1AEcARAAAIAA1AEgASQANAAoAAgA8AAkACgANAA4ADwBDABEAEgATABQAFQBEABcARQAZAEYAGgBAADsAQAKAIAA1AE4ASwAAIAA1AE8AFgANAAoAAgA8AAkACgANAA4ADwBKABEAEg'
..'ATABQAFQBLABcATAAZAE0AGgBAADsAQAKAIAA1AFQAUQAAIAA1AFUAJQANAAoAAgA8AAkACgANAA4ADwBQABEAEgATABQAFQBRABcAUgAZAFMAGgBAADsAQAKAIAA1AFgAPgAAIAA1AFkAKgANAAoAAgA8AAkACgANAA4ADwBWABEAEgATABQAFQA+ABcAVwAZAD4AGgBAAAYAAQABAAIAWgABA'
..'BMAAgACAFsABABcAAEAFAACAAIAXQAEAF4AOwBAAoAgADUAYQBLAAAgADUAYgAWABUACgACADwACQAKAA0ADgAPAF8AEQASABMAFAAVAEsAFwBgABkATQAaAEAAOwBAAoAgADUAZQBRAAAgADUAZgAlABUACgACADwACQAKAA0ADgAPAGMAEQASABMAFAAVAFEAFwBkABkAUwAaAEAAOwBAAoAg'
..'ADUAaQA+AAAgADUAagAqABUACgACADwACQAKAA0ADgAPAGcAEQASABMAFAAVAD4AFwBoABkAPgAaAEAAOwBAAoAgADUAbQBEAAAgADUAbgBJABUACgACADwACQAKAA0ADgAPAGsAEQASABMAFAAVAEQAFwBsABkARgAaAEAAIAAVAAoACQAKAAsADAANAA4ADwBvABEAEgATABQAFQAlABcAcAA'
..'ZACcAGgBxACAAFQAIAAkACgALAAwADQAOAA8AcgARABIAEwAUABcAcwAaAHEAIAAVAAoACQAKAAsADAANAA4ADwB0ABEAEgATABQAFQAWABcAdQAZABYAGgA1ACAAFQAKAAkACgALAAwADQAOAA8AdgARABIAEwAUABUAKgAXAHcAGQAqABoANQAIABQACwAJAAoACwAMAA0ADgAPAHgAEQASAB'
..'MAFAAVABYAFwB5ABkAFgAaAHoAHAAMAAEAFAACAAIAXQAEAHsAOwBAAoAgADUAfgB9AAAgADUAfgB/AB8ACgACADwACQAKAA0ADgAPAHwAEQASABMAFAAVAH0AFwB+ABkAfQAaAEAAOwBAAoAgADUAggCBAAAgADUAggCEAB8ACgACADwACQAKAA0ADgAPAIAAEQASABMAFAAVAIEAFwCCABkAg'
..'wAaAEAAOwBAAoAgADUAhwCGAAAgADUAhwCJAB8ACgACADwACQAKAA0ADgAPAIUAEQASABMAFAAVAIYAFwCHABkAiAAaAEAAOwBAAoAgADUAjACLAAAgADUAjACOAB8ACgACADwACQAKAA0ADgAPAIoAEQASABMAFAAVAIsAFwCMABkAjQAaAEAAIAAfAAoACQAKAAsADAANAA4ADwCPABEAEgAT'
..'ABQAFQCEABcAkAAZAJEAGgBxACAAHwAKAAkACgALAAwADQAOAA8AkgARABIAEwAUABUAjgAXAJMAGQCUABoAcQAgAB8ACgAJAAoACwAMAA0ADgAPAJUAEQASABMAFAAVAH8AFwCWABkAlwAaADUAIAAfAAoACQAKAAsADAANAA4ADwCYABEAEgATABQAFQCJABcAmQAZAJoAGgA1AAgAEwANAAI'
..'AWwAJAAoACwAMAA0ADgAPAJsAEQASABMAFAAVABYAFwCcABkAFgAaAJ0AHAAMAJ4AnwAIABMADQACAFsACQAKAAsADAANAA4ADwCgABEAEgATABQAFQAWABcAoQAZABYAGgCiABwADACeAJ8ABgABAAEAAgCjAAEAKgACAAIApAAEAKUACAArAAsACQAKAAsADAANAA4ADwCmABEAEgATABQAFQ'
..'AWABcApwAZABYAGgCoABwADAABACsAAgACAF0ABACpADsAQAKAIAA1AKwASwAAIAA1AK0AFgAtAAoAAgA8AAkACgANAA4ADwCqABEAEgATABQAFQBLABcAqwAZAE0AGgBAADsAQAKAIAA1ALAAUQAAIAA1ALEAJQAtAAoAAgA8AAkACgANAA4ADwCuABEAEgATABQAFQBRABcArwAZAFMAGgBAA'
..'DsAQAKAIAA1ALQAPgAAIAA1ALUAKgAtAAoAAgA8AAkACgANAA4ADwCyABEAEgATABQAFQA+ABcAswAZAD4AGgBAACAALQAKAAkACgALAAwADQAOAA8AtgARABIAEwAUABUAJQAXALcAGQAnABoANQAgAC0ACgAJAAoACwAMAA0ADgAPALgAEQASABMAFAAVACoAFwC5ABkAKgAaADUAOwBAAoAg'
..'ADUAvABEAAAgADUAvQBJAC0ACgACADwACQAKAA0ADgAPALoAEQASABMAFAAVAEQAFwC7ABkARgAaAEAAIAAtAAgACQAKAAsADAANAA4ADwC+ABEAEgATABQAFwC/ABoANQAgAC0ACgAJAAoACwAMAA0ADgAPAMAAEQASABMAFAAVABYAFwDBABkAFgAaADUAAQArAAIAAgBdAAQAwgA7AEACgCA'
..'ANQDFAH0AACAANQDEAH8ANgAKAAIAPAAJAAoADQAOAA8AwwARABIAEwAUABUAfQAXAMQAGQB9ABoAQAA7AEACgCAANQDIAIEAACAANQDHAIQANgAKAAIAPAAJAAoADQAOAA8AxgARABIAEwAUABUAgQAXAMcAGQCDABoAQAA7AEACgCAANQDLAIYAACAANQDKAIkANgAKAAIAPAAJAAoADQAOAA'
..'8AyQARABIAEwAUABUAhgAXAMoAGQCIABoAQAAgADYACgAJAAoACwAMAA0ADgAPAMwAEQASABMAFAAVAIQAFwDNABkAkQAaADUAIAA2AAoACQAKAAsADAANAA4ADwDOABEAEgATABQAFQCJABcAzwAZAJoAGgA1ADsAQAKAIAA1ANIAiwAAIAA1ANEAjgA2AAoAAgA8AAkACgANAA4ADwDQABEAE'
..'gATABQAFQCLABcA0QAZAI0AGgBAACAANgAKAAkACgALAAwADQAOAA8A0wARABIAEwAUABUAjgAXANQAGQCUABoANQAgADYACgAJAAoACwAMAA0ADgAPANUAEQASABMAFAAVAH8AFwDWABkAlwAaADUAAQAqAAIAAgDXAAQA2AAIAD8ACwAJAAoACwAMAA0ADgAPANkAEQASABMAFAAVABYAFwDa'
..'ABkAFgAaANsAHAAMAAEAPwACAAIAXQAEANwAOwBAAoAgADUA3wB9AAAgADUA3gB/AEEACgACADwACQAKAA0ADgAPAN0AEQASABMAFAAVAH0AFwDeABkAfQAaAEAAOwBAAoAgADUA4gCBAAAgADUA4QCEAEEACgACADwACQAKAA0ADgAPAOAAEQASABMAFAAVAIEAFwDhABkAgwAaAEAAOwBAAoA'
..'gADUA5QCGAAAgADUA5ACJAEEACgACADwACQAKAA0ADgAPAOMAEQASABMAFAAVAIYAFwDkABkAiAAaAEAAIABBAAoACQAKAAsADAANAA4ADwDmABEAEgATABQAFQCEABcA5wAZAJEAGgA1ACAAQQAKAAkACgALAAwADQAOAA8A6AARABIAEwAUABUAiQAXAOkAGQCaABoANQA7AEACgCAANQDsAI'
..'sAACAANQDrAI4AQQAKAAIAPAAJAAoADQAOAA8A6gARABIAEwAUABUAiwAXAOsAGQCNABoAQAAgAEEACgAJAAoACwAMAA0ADgAPAO0AEQASABMAFAAVAI4AFwDuABkAlAAaADUAIABBAAoACQAKAAsADAANAA4ADwDvABEAEgATABQAFQB/ABcA8AAZAJcAGgA1AAEAPwACAAIAXQAEAPEAOwBAA'
..'oAgADUA9ABLAAAgADUA9QAWAEoACgACADwACQAKAA0ADgAPAPIAEQASABMAFAAVAEsAFwDzABkATQAaAEAAOwBAAoAgADUA+ABRAAAgADUA+QAlAEoACgACADwACQAKAA0ADgAPAPYAEQASABMAFAAVAFEAFwD3ABkAUwAaAEAAOwBAAoAgADUA/AA+AAAgADUA/QAqAEoACgACADwACQAKAA0A'
..'DgAPAPoAEQASABMAFAAVAD4AFwD7ABkAPgAaAEAAIABKAAoACQAKAAsADAANAA4ADwD+ABEAEgATABQAFQAlABcA/wAZACcAGgA1ACAASgAKAAkACgALAAwADQAOAA8AAAERABIAEwAUABUAKgAXAAEBGQAqABoANQA7AEACgCAANQAEAUQAACAANQAFAUkASgAKAAIAPAAJAAoADQAOAA8AAgE'
..'RABIAEwAUABUARAAXAAMBGQBGABoAQAAgAEoACAAJAAoACwAMAA0ADgAPAAYBEQASABMAFAAXAAcBGgA1ACAASgAKAAkACgALAAwADQAOAA8ACAERABIAEwAUABUAFgAXAAkBGQAWABoANQAIAD8ADAAJAAoACwAMAA0ADgAPAAoBCwEMAREAEgATABQAFQAWABcADQEZABYAGgAOARwADAABAD'
..'8AAgACAF0ABAAPATsAQAKAIAA1ABEBfQAAIAA1ABEBfwBUAAoAAgA8AAkACgANAA4ADwAQAREAEgATABQAFQB9ABcAEQEZAH0AGgBAADsAQAKAIAA1ABMBgQAAIAA1ABMBhABUAAoAAgA8AAkACgANAA4ADwASAREAEgATABQAFQCBABcAEwEZAIMAGgBAADsAQAKAIAA1ABUBhgAAIAA1ABUBi'
..'QBUAAoAAgA8AAkACgANAA4ADwAUAREAEgATABQAFQCGABcAFQEZAIgAGgBAACAAVAAKAAkACgALAAwADQAOAA8AFgERABIAEwAUABUAhAAXABcBGQCRABoANQAgAFQACgAJAAoACwAMAA0ADgAPABgBEQASABMAFAAVAIkAFwAZARkAmgAaADUAOwBAAoAgADUAGwGLAAAgADUAGwGOAFQACgAC'
..'ADwACQAKAA0ADgAPABoBEQASABMAFAAVAIsAFwAbARkAjQAaAEAAIABUAAoACQAKAAsADAANAA4ADwAcAREAEgATABQAFQCOABcAHQEZAJQAGgA1ACAAVAAKAAkACgALAAwADQAOAA8AHgERABIAEwAUABUAfwAXAB8BGQCXABoANQABACoAAgACACABBAAhAQgAXQALAAkACgALAAwADQAOAA8'
..'AIgERABIAEwAUABUAFgAXACMBGQAWABoAJAEcAAwAAQBdAAIAAgBdAAQAJQE7AEACgCAANQAoAUsAACAANQApARYAXwAKAAIAPAAJAAoADQAOAA8AJgERABIAEwAUABUASwAXACcBGQBNABoAQAA7AEACgCAANQAsAVEAACAANQAtASUAXwAKAAIAPAAJAAoADQAOAA8AKgERABIAEwAUABUAUQ'
..'AXACsBGQBTABoAQAA7AEACgCAANQAwAT4AACAANQAxASoAXwAKAAIAPAAJAAoADQAOAA8ALgERABIAEwAUABUAPgAXAC8BGQA+ABoAQAAgAF8ACgAJAAoACwAMAA0ADgAPADIBEQASABMAFAAVACUAFwAzARkAJwAaADUAIABfAAoACQAKAAsADAANAA4ADwA0AREAEgATABQAFQAqABcANQEZA'
..'CoAGgA1ADsAQAKAIAA1ADgBRAAAIAA1ADkBSQBfAAoAAgA8AAkACgANAA4ADwA2AREAEgATABQAFQBEABcANwEZAEYAGgBAACAAXwAIAAkACgALAAwADQAOAA8AOgERABIAEwAUABcAOwEaADUAIABfAAoACQAKAAsADAANAA4ADwA8AREAEgATABQAFQAWABcAPQEZABYAGgA1AAEAXQACAAIA'
..'XQAEAD4BOwBAAoAgADUAQAF9AAAgADUAQAF/AGgACgACADwACQAKAA0ADgAPAD8BEQASABMAFAAVAH0AFwBAARkAfQAaAEAAOwBAAoAgADUAQgGBAAAgADUAQgGEAGgACgACADwACQAKAA0ADgAPAEEBEQASABMAFAAVAIEAFwBCARkAgwAaAEAAOwBAAoAgADUARAGGAAAgADUARAGJAGgACgA'
..'CADwACQAKAA0ADgAPAEMBEQASABMAFAAVAIYAFwBEARkAiAAaAEAAIABoAAoACQAKAAsADAANAA4ADwBFAREAEgATABQAFQCEABcARgEZAJEAGgA1ACAAaAAKAAkACgALAAwADQAOAA8ARwERABIAEwAUABUAiQAXAEgBGQCaABoANQA7AEACgCAANQBKAYsAACAANQBKAY4AaAAKAAIAPAAJAA'
..'oADQAOAA8ASQERABIAEwAUABUAiwAXAEoBGQCNABoAQAAgAGgACgAJAAoACwAMAA0ADgAPAEsBEQASABMAFAAVAI4AFwBMARkAlAAaADUAIABoAAoACQAKAAsADAANAA4ADwBNAREAEgATABQAFQB/ABcATgEZAJcAGgA1AAEAKgACAAIATwEEAFABCABxAAsACQAKAAsADAANAA4ADwBRAREAE'
..'gATABQAFQAWABcAUgEZABYAGgAkARwADAABAHEAAgACAF0ABABTATsAQAKAIAA1AFYBSwAAIAA1AFcBFgBzAAoAAgA8AAkACgANAA4ADwBUAREAEgATABQAFQBLABcAVQEZAE0AGgBAADsAQAKAIAA1AFoBUQAAIAA1AFsBJQBzAAoAAgA8AAkACgANAA4ADwBYAREAEgATABQAFQBRABcAWQEZ'
..'AFMAGgBAADsAQAKAIAA1AF4BPgAAIAA1AF8BKgBzAAoAAgA8AAkACgANAA4ADwBcAREAEgATABQAFQA+ABcAXQEZAD4AGgBAACAAcwAKAAkACgALAAwADQAOAA8AYAERABIAEwAUABUAJQAXAGEBGQAnABoANQAgAHMACgAJAAoACwAMAA0ADgAPAGIBEQASABMAFAAVACoAFwBjARkAKgAaADU'
..'AOwBAAoAgADUAZgFEAAAgADUAZwFJAHMACgACADwACQAKAA0ADgAPAGQBEQASABMAFAAVAEQAFwBlARkARgAaAEAAIABzAAgACQAKAAsADAANAA4ADwBoAREAEgATABQAFwBpARoANQAgAHMACgAJAAoACwAMAA0ADgAPAGoBEQASABMAFAAVABYAFwBrARkAFgAaADUAAQBxAAIAAgBdAAQAbA'
..'E7AEACgCAANQBuAX0AACAANQBuAX8AfAAKAAIAPAAJAAoADQAOAA8AbQERABIAEwAUABUAfQAXAG4BGQB9ABoAQAA7AEACgCAANQBwAYEAACAANQBwAYQAfAAKAAIAPAAJAAoADQAOAA8AbwERABIAEwAUABUAgQAXAHABGQCDABoAQAA7AEACgCAANQByAYYAACAANQByAYkAfAAKAAIAPAAJA'
..'AoADQAOAA8AcQERABIAEwAUABUAhgAXAHIBGQCIABoAQAAgAHwACgAJAAoACwAMAA0ADgAPAHMBEQASABMAFAAVAIQAFwB0ARkAkQAaADUAIAB8AAoACQAKAAsADAANAA4ADwB1AREAEgATABQAFQCJABcAdgEZAJoAGgA1ADsAQAKAIAA1AHgBiwAAIAA1AHgBjgB8AAoAAgA8AAkACgANAA4A'
..'DwB3AREAEgATABQAFQCLABcAeAEZAI0AGgBAACAAfAAKAAkACgALAAwADQAOAA8AeQERABIAEwAUABUAjgAXAHoBGQCUABoANQAgAHwACgAJAAoACwAMAA0ADgAPAHsBEQASABMAFAAVAH8AFwB8ARkAlwAaADUAAQAqAAIAAgB9AQQAfgEIAIUACwAJAAoACwAMAA0ADgAPAH8BEQASABMAFAA'
..'VABYAFwCAARkAFgAaAIEBHAAMAAEAhQACAAIAXQAEAIIBOwBAAoAgADUAhQFLAAAgADUAhgEWAIcACgACADwACQAKAA0ADgAPAIMBEQASABMAFAAVAEsAFwCEARkATQAaAEAAOwBAAoAgADUAiQFRAAAgADUAigElAIcACgACADwACQAKAA0ADgAPAIcBEQASABMAFAAVAFEAFwCIARkAUwAaAE'
..'AAOwBAAoAgADUAjQE+AAAgADUAjgEqAIcACgACADwACQAKAA0ADgAPAIsBEQASABMAFAAVAD4AFwCMARkAPgAaAEAAIACHAAoACQAKAAsADAANAA4ADwCPAREAEgATABQAFQAlABcAkAEZACcAGgA1ACAAhwAKAAkACgALAAwADQAOAA8AkQERABIAEwAUABUAKgAXAJIBGQAqABoANQA7AEACg'
..'CAANQCVAUQAACAANQCWAUkAhwAKAAIAPAAJAAoADQAOAA8AkwERABIAEwAUABUARAAXAJQBGQBGABoAQAAgAIcACAAJAAoACwAMAA0ADgAPAJcBEQASABMAFAAXAJgBGgA1ACAAhwAKAAkACgALAAwADQAOAA8AmQERABIAEwAUABUAFgAXAJoBGQAWABoANQABAIUAAgACAF0ABACbATsAQAKA'
..'IAA1AJ0BfQAAIAA1AJ0BfwCQAAoAAgA8AAkACgANAA4ADwCcAREAEgATABQAFQB9ABcAnQEZAH0AGgBAADsAQAKAIAA1AJ8BgQAAIAA1AJ8BhACQAAoAAgA8AAkACgANAA4ADwCeAREAEgATABQAFQCBABcAnwEZAIMAGgBAADsAQAKAIAA1AKEBhgAAIAA1AKEBiQCQAAoAAgA8AAkACgANAA4'
..'ADwCgAREAEgATABQAFQCGABcAoQEZAIgAGgBAACAAkAAKAAkACgALAAwADQAOAA8AogERABIAEwAUABUAhAAXAKMBGQCRABoANQAgAJAACgAJAAoACwAMAA0ADgAPAKQBEQASABMAFAAVAIkAFwClARkAmgAaADUAOwBAAoAgADUApwGLAAAgADUApwGOAJAACgACADwACQAKAA0ADgAPAKYBEQ'
..'ASABMAFAAVAIsAFwCnARkAjQAaAEAAIACQAAoACQAKAAsADAANAA4ADwCoAREAEgATABQAFQCOABcAqQEZAJQAGgA1ACAAkAAKAAkACgALAAwADQAOAA8AqgERABIAEwAUABUAfwAXAKsBGQCXABoANQABACoAAgACAKwBBACtAQEAmQACAAIAXQAEAK4BIACaAAoACQAKAAsADAANAA4ADwCvA'
..'REAEgATABQAFQCEABcAsAEZAJEAGgCxATsAQAKAIAA1ALMBgQAAIAA1ALMBhACaAAoAAgA8AAkACgANAA4ADwCyAREAEgATABQAFQCBABcAswEZAIMAGgBAACAAmgAKAAkACgALAAwADQAOAA8AtAERABIAEwAUABUAfwAXALUBGQCXABoANQA7AEACgCAANQC3AX0AACAANQC3AX8AmgAKAAIA'
..'PAAJAAoADQAOAA8AtgERABIAEwAUABUAfQAXALcBGQB9ABoAQAAgAJoACgAJAAoACwAMAA0ADgAPALgBEQASABMAFAAVAI4AFwC5ARkAlAAaALEBOwBAAoAgADUAuwGLAAAgADUAuwGOAJoACgACADwACQAKAA0ADgAPALoBEQASABMAFAAVAIsAFwC7ARkAjQAaAEAAIACaAAoACQAKAAsADAA'
..'NAA4ADwC8AREAEgATABQAFQCJABcAvQEZAJoAGgA1ADsAQAKAIAA1AL8BhgAAIAA1AL8BiQCaAAoAAgA8AAkACgANAA4ADwC+AREAEgATABQAFQCGABcAvwEZAIgAGgBAAAgAmQALAAkACgALAAwADQAOAA8AwAERABIAEwAUABUAFgAXAMEBGQAWABoAwgEcAAwACACZAAsACQAKAAsADAANAA'
..'4ADwDDAREAEgATABQAFQAWABcAxAEZABYAGgDFARwADAABAJkAAgACAF0ABADGASAApQAKAAkACgALAAwADQAOAA8AxwERABIAEwAUABUAJQAXAMgBGQAnABoAsQE7AEACgCAANQDLAVEAACAANQDMASUApQAKAAIAPAAJAAoADQAOAA8AyQERABIAEwAUABUAUQAXAMoBGQBTABoAQAAgAKUAC'
..'gAJAAoACwAMAA0ADgAPAM0BEQASABMAFAAVABYAFwDOARkAFgAaADUAOwBAAoAgADUA0QFLAAAgADUA0gEWAKUACgACADwACQAKAA0ADgAPAM8BEQASABMAFAAVAEsAFwDQARkATQAaAEAAIAClAAgACQAKAAsADAANAA4ADwDTAREAEgATABQAFwDUARoAsQE7AEACgCAANQDXAUQAACAANQDY'
..'AUkApQAKAAIAPAAJAAoADQAOAA8A1QERABIAEwAUABUARAAXANYBGQBGABoAQAAgAKUACgAJAAoACwAMAA0ADgAPANkBEQASABMAFAAVACoAFwDaARkAKgAaADUAOwBAAoAgADUA3QE+AAAgADUA3gEqAKUACgACADwACQAKAA0ADgAPANsBEQASABMAFAAVAD4AFwDcARkAPgAaAEAACACZAAs'
..'ACQAKAAsADAANAA4ADwDfAREAEgATABQAFQAWABcA4AEZABYAGgDhARwADAABACoAAgACAOIBBADjAQgArwALAAkACgALAAwADQAOAA8A5AERABIAEwAUABUAFgAXAOUBGQAWABoAJAEcAAwAAQCvAAIAAgBdAAQA5gE7AEACgCAANQDpAUsAACAANQDqARYAsQAKAAIAPAAJAAoADQAOAA8A5w'
..'ERABIAEwAUABUASwAXAOgBGQBNABoAQAA7AEACgCAANQDtAVEAACAANQDuASUAsQAKAAIAPAAJAAoADQAOAA8A6wERABIAEwAUABUAUQAXAOwBGQBTABoAQAA7AEACgCAANQDxAT4AACAANQDyASoAsQAKAAIAPAAJAAoADQAOAA8A7wERABIAEwAUABUAPgAXAPABGQA+ABoAQAAgALEACgAJA'
..'AoACwAMAA0ADgAPAPMBEQASABMAFAAVACUAFwD0ARkAJwAaADUAIACxAAoACQAKAAsADAANAA4ADwD1AREAEgATABQAFQAqABcA9gEZACoAGgA1ADsAQAKAIAA1APkBRAAAIAA1APoBSQCxAAoAAgA8AAkACgANAA4ADwD3AREAEgATABQAFQBEABcA+AEZAEYAGgBAACAAsQAIAAkACgALAAwA'
..'DQAOAA8A+wERABIAEwAUABcA/AEaADUAIACxAAoACQAKAAsADAANAA4ADwD9AREAEgATABQAFQAWABcA/gEZABYAGgA1AAEArwACAAIAXQAEAP8BOwBAAoAgADUAAQJ9AAAgADUAAQJ/ALoACgACADwACQAKAA0ADgAPAAACEQASABMAFAAVAH0AFwABAhkAfQAaAEAAOwBAAoAgADUAAwKBAAA'
..'gADUAAwKEALoACgACADwACQAKAA0ADgAPAAICEQASABMAFAAVAIEAFwADAhkAgwAaAEAAOwBAAoAgADUABQKGAAAgADUABQKJALoACgACADwACQAKAA0ADgAPAAQCEQASABMAFAAVAIYAFwAFAhkAiAAaAEAAIAC6AAoACQAKAAsADAANAA4ADwAGAhEAEgATABQAFQCEABcABwIZAJEAGgA1AC'
..'AAugAKAAkACgALAAwADQAOAA8ACAIRABIAEwAUABUAiQAXAAkCGQCaABoANQA7AEACgCAANQALAosAACAANQALAo4AugAKAAIAPAAJAAoADQAOAA8ACgIRABIAEwAUABUAiwAXAAsCGQCNABoAQAAgALoACgAJAAoACwAMAA0ADgAPAAwCEQASABMAFAAVAI4AFwANAhkAlAAaADUAIAC6AAoAC'
..'QAKAAsADAANAA4ADwAOAhEAEgATABQAFQB/ABcADwIZAJcAGgA1AAEAKgACAAIAEAIEABECCADDAAsACQAKAAsADAANAA4ADwASAhEAEgATABQAFQAWABcAEwIZABYAGgAUAhwADAABAMMAAgACAF0ABAAVAjsAQAKAIAA1ABgCSwAAIAA1ABkCFgDFAAoAAgA8AAkACgANAA4ADwAWAhEAEgAT'
..'ABQAFQBLABcAFwIZAE0AGgBAADsAQAKAIAA1ABwCUQAAIAA1AB0CJQDFAAoAAgA8AAkACgANAA4ADwAaAhEAEgATABQAFQBRABcAGwIZAFMAGgBAADsAQAKAIAA1ACACPgAAIAA1ACECKgDFAAoAAgA8AAkACgANAA4ADwAeAhEAEgATABQAFQA+ABcAHwIZAD4AGgBAACAAxQAKAAkACgALAAw'
..'ADQAOAA8AIgIRABIAEwAUABUAJQAXACMCGQAnABoANQAgAMUACgAJAAoACwAMAA0ADgAPACQCEQASABMAFAAVACoAFwAlAhkAKgAaADUAOwBAAoAgADUAKAJEAAAgADUAKQJJAMUACgACADwACQAKAA0ADgAPACYCEQASABMAFAAVAEQAFwAnAhkARgAaAEAAIADFAAgACQAKAAsADAANAA4ADw'
..'AqAhEAEgATABQAFwArAhoANQAgAMUACgAJAAoACwAMAA0ADgAPACwCEQASABMAFAAVABYAFwAtAhkAFgAaADUAAQDDAAIAAgBdAAQALgI7AEACgCAANQAwAn0AACAANQAwAn8AzgAKAAIAPAAJAAoADQAOAA8ALwIRABIAEwAUABUAfQAXADACGQB9ABoAQAA7AEACgCAANQAyAoEAACAANQAyA'
..'oQAzgAKAAIAPAAJAAoADQAOAA8AMQIRABIAEwAUABUAgQAXADICGQCDABoAQAA7AEACgCAANQA0AoYAACAANQA0AokAzgAKAAIAPAAJAAoADQAOAA8AMwIRABIAEwAUABUAhgAXADQCGQCIABoAQAAgAM4ACgAJAAoACwAMAA0ADgAPADUCEQASABMAFAAVAIQAFwA2AhkAkQAaADUAIADOAAoA'
..'CQAKAAsADAANAA4ADwA3AhEAEgATABQAFQCJABcAOAIZAJoAGgA1ADsAQAKAIAA1ADoCiwAAIAA1ADoCjgDOAAoAAgA8AAkACgANAA4ADwA5AhEAEgATABQAFQCLABcAOgIZAI0AGgBAACAAzgAKAAkACgALAAwADQAOAA8AOwIRABIAEwAUABUAjgAXADwCGQCUABoANQAgAM4ACgAJAAoACwA'
..'MAA0ADgAPAD0CEQASABMAFAAVAH8AFwA+AhkAlwAaADUAAQAqAAIAAgA/AgQAQAIIANcACwAJAAoACwAMAA0ADgAPAEECEQASABMAFAAVABYAFwBCAhkAFgAaABQCHAAMAAEA1wACAAIAXQAEAEMCOwBAAoAgADUARgJLAAAgADUARwIWANkACgACADwACQAKAA0ADgAPAEQCEQASABMAFAAVAE'
..'sAFwBFAhkATQAaAEAAOwBAAoAgADUASgJRAAAgADUASwIlANkACgACADwACQAKAA0ADgAPAEgCEQASABMAFAAVAFEAFwBJAhkAUwAaAEAAOwBAAoAgADUATgI+AAAgADUATwIqANkACgACADwACQAKAA0ADgAPAEwCEQASABMAFAAVAD4AFwBNAhkAPgAaAEAAIADZAAoACQAKAAsADAANAA4AD'
..'wBQAhEAEgATABQAFQAlABcAUQIZACcAGgA1ACAA2QAKAAkACgALAAwADQAOAA8AUgIRABIAEwAUABUAKgAXAFMCGQAqABoANQA7AEACgCAANQBWAkQAACAANQBXAkkA2QAKAAIAPAAJAAoADQAOAA8AVAIRABIAEwAUABUARAAXAFUCGQBGABoAQAAgANkACAAJAAoACwAMAA0ADgAPAFgCEQAS'
..'ABMAFAAXAFkCGgA1ACAA2QAKAAkACgALAAwADQAOAA8AWgIRABIAEwAUABUAFgAXAFsCGQAWABoANQABANcAAgACAF0ABABcAjsAQAKAIAA1AF4CfQAAIAA1AF4CfwDiAAoAAgA8AAkACgANAA4ADwBdAhEAEgATABQAFQB9ABcAXgIZAH0AGgBAADsAQAKAIAA1AGACgQAAIAA1AGAChADiAAo'
..'AAgA8AAkACgANAA4ADwBfAhEAEgATABQAFQCBABcAYAIZAIMAGgBAADsAQAKAIAA1AGIChgAAIAA1AGICiQDiAAoAAgA8AAkACgANAA4ADwBhAhEAEgATABQAFQCGABcAYgIZAIgAGgBAACAA4gAKAAkACgALAAwADQAOAA8AYwIRABIAEwAUABUAhAAXAGQCGQCRABoANQAgAOIACgAJAAoACw'
..'AMAA0ADgAPAGUCEQASABMAFAAVAIkAFwBmAhkAmgAaADUAOwBAAoAgADUAaAKLAAAgADUAaAKOAOIACgACADwACQAKAA0ADgAPAGcCEQASABMAFAAVAIsAFwBoAhkAjQAaAEAAIADiAAoACQAKAAsADAANAA4ADwBpAhEAEgATABQAFQCOABcAagIZAJQAGgA1ACAA4gAKAAkACgALAAwADQAOA'
..'A8AawIRABIAEwAUABUAfwAXAGwCGQCXABoANQABACoAAgACAG0CBABuAggA6wALAAkACgALAAwADQAOAA8AbwIRABIAEwAUABUAFgAXAHACGQAWABoAcQIcAAwAAQDrAAIAAgBdAAQAcgI7AEACgCAANQB1AksAACAANQB2AhYA7QAKAAIAPAAJAAoADQAOAA8AcwIRABIAEwAUABUASwAXAHQC'
..'GQBNABoAQAA7AEACgCAANQB5AlEAACAANQB6AiUA7QAKAAIAPAAJAAoADQAOAA8AdwIRABIAEwAUABUAUQAXAHgCGQBTABoAQAA7AEACgCAANQB9Aj4AACAANQB+AioA7QAKAAIAPAAJAAoADQAOAA8AewIRABIAEwAUABUAPgAXAHwCGQA+ABoAQAAgAO0ACgAJAAoACwAMAA0ADgAPAH8CEQA'
..'SABMAFAAVACUAFwCAAhkAJwAaADUAIADtAAoACQAKAAsADAANAA4ADwCBAhEAEgATABQAFQAqABcAggIZACoAGgA1ADsAQAKAIAA1AIUCRAAAIAA1AIYCSQDtAAoAAgA8AAkACgANAA4ADwCDAhEAEgATABQAFQBEABcAhAIZAEYAGgBAACAA7QAIAAkACgALAAwADQAOAA8AhwIRABIAEwAUAB'
..'cAiAIaADUAIADtAAoACQAKAAsADAANAA4ADwCJAhEAEgATABQAFQAWABcAigIZABYAGgA1AAEA6wACAAIAXQAEAIsCOwBAAoAgADUAjQKBAAAgADUAjQKEAPYACgACADwACQAKAA0ADgAPAIwCEQASABMAFAAVAIEAFwCNAhkAgwAaAEAAOwBAAoAgADUAjwKGAAAgADUAjwKJAPYACgACADwAC'
..'QAKAA0ADgAPAI4CEQASABMAFAAVAIYAFwCPAhkAiAAaAEAAIAD2AAoACQAKAAsADAANAA4ADwCQAhEAEgATABQAFQCEABcAkQIZAJEAGgA1ACAA9gAKAAkACgALAAwADQAOAA8AkgIRABIAEwAUABUAiQAXAJMCGQCaABoANQA7AEACgCAANQCVAosAACAANQCVAo4A9gAKAAIAPAAJAAoADQAO'
..'AA8AlAIRABIAEwAUABUAiwAXAJUCGQCNABoAQAAgAPYACgAJAAoACwAMAA0ADgAPAJYCEQASABMAFAAVAI4AFwCXAhkAlAAaAJgCIAD2AAoACQAKAAsADAANAA4ADwCZAhEAEgATABQAFQB/ABcAmgIZAJcAGgA1ADsAQAKAIAA1AJwCfQAAIAA1AJwCfwD2AAoAAgA8AAkACgANAA4ADwCbAhE'
..'AEgATABQAFQB9ABcAnAIZAH0AGgBAAAEAKgACAAIAnQIEAJ4CCAD/AAwACQAKAAsADAANAA4ADwCfAgsBDAERABIAEwAUABUAFgAXAKACGQAWABoAoQIcAAwAAQD/AAIAAgBdAAQAogI7AEACgCAANQClAksAACAANQCmAhYAAQEKAAIAPAAJAAoADQAOAA8AowIRABIAEwAUABUASwAXAKQCGQ'
..'BNABoAQAA7AEACgCAANQCpAlEAACAANQCqAiUAAQEKAAIAPAAJAAoADQAOAA8ApwIRABIAEwAUABUAUQAXAKgCGQBTABoAQAA7AEACgCAANQCtAj4AACAANQCuAioAAQEKAAIAPAAJAAoADQAOAA8AqwIRABIAEwAUABUAPgAXAKwCGQA+ABoAQAAgAAEBCgAJAAoACwAMAA0ADgAPAK8CEQASA'
..'BMAFAAVACUAFwCwAhkAJwAaADUAIAABAQoACQAKAAsADAANAA4ADwCxAhEAEgATABQAFQAqABcAsgIZACoAGgA1ADsAQAKAIAA1ALUCRAAAIAA1ALYCSQABAQoAAgA8AAkACgANAA4ADwCzAhEAEgATABQAFQBEABcAtAIZAEYAGgBAACAAAQEIAAkACgALAAwADQAOAA8AtwIRABIAEwAUABcA'
..'uAIaADUAIAABAQoACQAKAAsADAANAA4ADwC5AhEAEgATABQAFQAWABcAugIZABYAGgA1AAEA/wACAAIAXQAEALsCOwBAAoAgADUAvQJ9AAAgADUAvQJ/AAoBCgACADwACQAKAA0ADgAPALwCEQASABMAFAAVAH0AFwC9AhkAfQAaAEAAOwBAAoAgADUAvwKBAAAgADUAvwKEAAoBCgACADwACQA'
..'KAA0ADgAPAL4CEQASABMAFAAVAIEAFwC/AhkAgwAaAEAAOwBAAoAgADUAwQKGAAAgADUAwQKJAAoBCgACADwACQAKAA0ADgAPAMACEQASABMAFAAVAIYAFwDBAhkAiAAaAEAAIAAKAQoACQAKAAsADAANAA4ADwDCAhEAEgATABQAFQCEABcAwwIZAJEAGgA1ACAACgEKAAkACgALAAwADQAOAA'
..'8AxAIRABIAEwAUABUAiQAXAMUCGQCaABoANQA7AEACgCAANQDHAosAACAANQDHAo4ACgEKAAIAPAAJAAoADQAOAA8AxgIRABIAEwAUABUAiwAXAMcCGQCNABoAQAAgAAoBCgAJAAoACwAMAA0ADgAPAMgCEQASABMAFAAVAI4AFwDJAhkAlAAaADUAIAAKAQoACQAKAAsADAANAA4ADwDKAhEAE'
..'gATABQAFQB/ABcAywIZAJcAGgA1AAgA/wAMAAkACgALAAwADQAOAA8AzAILAQwBEQASABMAFAAVABYAFwDNAhkAFgAaAM4CHAAMAAEAKgACAAIAzwIEANACCAAUAQsACQAKAAsADAANAA4ADwDRAhEAEgATABQAFQAWABcA0gIZABYAGgDTAhwADAABABQBAgACAF0ABADUAjsAQAKAIAA1ANcC'
..'SwAAIAA1ANgCFgAWAQoAAgA8AAkACgANAA4ADwDVAhEAEgATABQAFQBLABcA1gIZAE0AGgBAADsAQAKAIAA1ANsCUQAAIAA1ANwCJQAWAQoAAgA8AAkACgANAA4ADwDZAhEAEgATABQAFQBRABcA2gIZAFMAGgBAADsAQAKAIAA1AN8CPgAAIAA1AOACKgAWAQoAAgA8AAkACgANAA4ADwDdAhE'
..'AEgATABQAFQA+ABcA3gIZAD4AGgBAACAAFgEKAAkACgALAAwADQAOAA8A4QIRABIAEwAUABUAJQAXAOICGQAnABoANQAgABYBCgAJAAoACwAMAA0ADgAPAOMCEQASABMAFAAVACoAFwDkAhkAKgAaADUAOwBAAoAgADUA5wJEAAAgADUA6AJJABYBCgACADwACQAKAA0ADgAPAOUCEQASABMAFA'
..'AVAEQAFwDmAhkARgAaAEAAIAAWAQgACQAKAAsADAANAA4ADwDpAhEAEgATABQAFwDqAhoANQAgABYBCgAJAAoACwAMAA0ADgAPAOsCEQASABMAFAAVABYAFwDsAhkAFgAaADUAAQAUAQIAAgBdAAQA7QI7AEACgCAANQDvAn0AACAANQDvAn8AHwEKAAIAPAAJAAoADQAOAA8A7gIRABIAEwAUA'
..'BUAfQAXAO8CGQB9ABoAQAA7AEACgCAANQDxAoEAACAANQDxAoQAHwEKAAIAPAAJAAoADQAOAA8A8AIRABIAEwAUABUAgQAXAPECGQCDABoAQAA7AEACgCAANQDzAoYAACAANQDzAokAHwEKAAIAPAAJAAoADQAOAA8A8gIRABIAEwAUABUAhgAXAPMCGQCIABoAQAAgAB8BCgAJAAoACwAMAA0A'
..'DgAPAPQCEQASABMAFAAVAIQAFwD1AhkAkQAaADUAIAAfAQoACQAKAAsADAANAA4ADwD2AhEAEgATABQAFQCJABcA9wIZAJoAGgA1ADsAQAKAIAA1APkCiwAAIAA1APkCjgAfAQoAAgA8AAkACgANAA4ADwD4AhEAEgATABQAFQCLABcA+QIZAI0AGgBAACAAHwEKAAkACgALAAwADQAOAA8A+gI'
..'RABIAEwAUABUAjgAXAPsCGQCUABoANQAgAB8BCgAJAAoACwAMAA0ADgAPAPwCEQASABMAFAAVAH8AFwD9AhkAlwAaADUAAQAqAAIAAgD+AgQA/wIIACgBDAACAAADCQAKAAsADAANAA4ADwABAxEAEgATABQAFQACAxcAAwMZAAQDGgAFAxwADAAIACgBDAACAAADCQAKAAsADAANAA4ADwAGAx'
..'EAEgATABQAFQAHAxcACAMZAAkDGgAFAxwADAAIACgBDAACAAADCQAKAAsADAANAA4ADwAKAxEAEgATABQAFQALAxcADAMZAA0DGgAOAxwADAAIACgBDAACAAADCQAKAAsADAANAA4ADwAPAxEAEgATABQAFQAQAxcAEQMZABIDGgATAxwADAABACoAAgACABQDBAAVAwgALQEMAAIAAAMJAAoAC'
..'wAMAA0ADgAPABYDEQASABMAFAAVABcDFwAYAxkAGQMaAAUDHAAMAAgALQEMAAIAAAMJAAoACwAMAA0ADgAPABoDEQASABMAFAAVABsDFwAcAxkAHQMaAAUDHAAMAAgALQEMAAIAAAMJAAoACwAMAA0ADgAPAB4DEQASABMAFAAVAB8DFwAgAxkAIQMaAA4DHAAMAAgALQEMAAIAAAMJAAoACwAM'
..'AA0ADgAPACIDEQASABMAFAAVACMDFwAkAxkAJQMaACYDHAAMAAYAAQABAAIAJwMIADIBCwAJAAoACwAMAA0AKAMPACkDEQAqAxMAKwMVABYAFwAsAxkAFgAaAC0DHAAMAAgAMgELAAkACgALAAwADQAoAw8ALgMRACoDEwArAxUAFgAXAC8DGQAWABoAMAMcAAwACAAyAQsACQAKAAsADAANACg'
..'DDwAxAxEAKgMTACsDFQAWABcAMgMZABYAGgAzAxwADAAIADIBCwAJAAoACwAMAA0AKAMPADQDEQAqAxMAKwMVABYAFwA1AxkAFgAaADYDHAAMAAgAMgELAAkACgALAAwADQAoAw8ANwMRACoDEwArAxUAFgAXADgDGQAWABoAOQMcAAwACAAyAQsACQAKAAsADAANACgDDwA6AxEAKgMTACsDFQ'
..'AWABcAOwMZABYAGgA8AxwADAAIAAEADQACAD0DCQAKAAsADAANAD4DDwA/AwsBDAERAEADEwAUABUAFgAXAEEDGQAWABoAQgMcAAwAAA==')
for _,obj in pairs(Objects) do
	obj.Parent = script or workspace
end
